runtime: nodejs20

handlers:
  - url: /api/.*
    script: auto

  - url: /(.*\.(ico|gif|jpg|jpeg|png|txt|html|js|css|json|svg|woff2|woff|ttf|map))$
    static_files: client/dist/\1
    upload: client/dist/.*\.(ico|gif|jpg|jpeg|png|txt|html|js|css|json|svg|woff2|woff|ttf|map)$

  - url: /.*
    static_files: client/dist/index.html
    upload: client/dist/index.html
